- name: Creating alertmanager user group
  group: name="{{groupId}}"  # Create a user group with the specified group ID
  become: true  # Execute the task with elevated privileges

- name: Creating alertmanager user
  user:
    name: "{{userId}}"  # Create a user with the specified user ID
    group: "{{groupId}}"  # Assign the user to the specified group
    system: yes  # Create a system user
    shell: "/sbin/nologin"  # Set the user's shell to /sbin/nologin
    comment: "{{userId}} nologin User"  # Add a comment for the user
    createhome: "no"  # Do not create a home directory for the user
    state: present  # Ensure that the user is present

- name: Download alertmanager
  unarchive:
    src: "https://github.com/prometheus/alertmanager/releases/download/v{{ version }}/alertmanager-{{ version }}.linux-amd64.tar.gz"  # Download the alertmanager release archive
    dest: /tmp/  # Specify the destination directory for the downloaded file
    remote_src: yes  # Download the file from a remote source

- name: Copy alertmanager executable to bin
  copy:
    src: "/tmp/alertmanager-{{ version }}.linux-amd64/alertmanager"  # Specify the source path for the alertmanager executable
    dest: "/usr/local/bin/alertmanager"  # Specify the destination path for the alertmanager executable
    owner: "{{userId}}"  # Set the owner of the file to the specified user
    group: "{{groupId}}"  # Set the group of the file to the specified group
    remote_src: yes  # Copy the file from a remote source
    mode: 0755  # Set the file permissions to 0755

- name: Delete alertmanager tmp folder
  file:
    path: '/tmp/alertmanager-{{ version }}.linux-amd64'  # Specify the path to the temporary folder
    state: absent  # Remove the temporary folder

- name: Creates data directory
  file: 
    path: "/data/alertmanager/"  # Specify the path for the data directory
    state: directory  # Ensure that the directory exists
    owner: "{{userId}}"  # Set the owner of the directory to the specified user
    group: "{{groupId}}"  # Set the group of the directory to the specified group
    mode: 0755  # Set the directory permissions to 0755

- name: Creates config directory
  file: 
    path: "/etc/alertmanager/"  # Specify the path for the config directory
    state: directory  # Ensure that the directory exists
    owner: "{{userId}}"  # Set the owner of the directory to the specified user
    group: "{{groupId}}"  # Set the group of the directory to the specified group
    mode: 0755  # Set the directory permissions to 0755

- name: Copy config file
  copy:
    src: "{{ role_path }}/files/alertmanager.yml"  # Specify the source path for the config file
    dest: /etc/alertmanager/alertmanager.yml  # Specify the destination path for the config file

- name: Copy systemd init file
  template:
    src: init.service.j2  # Specify the source template for the systemd init file
    dest: /etc/systemd/system/alertmanager.service  # Specify the destination path for the systemd init file
  notify: systemd_reload  # Trigger the systemd reload handler

- name: Start alertmanager service
  service:
    name: alertmanager  # Specify the name of the alertmanager service
    state: started  # Start the service
    enabled: yes  # Enable the service to start on boot

- name: Check if alertmanager is accessible
  uri:
    url: http://localhost:9093  # Specify the URL to check
    method: GET  # Use the GET HTTP method
    status_code: 200  # Expect a 200 status code as a successful response
